## Q1. What are Eigenvalues and Eigenvectors? How are they related to the Eigen-Decomposition approach? Explain with an example.

Ans-Eigenvalues are the scalar values associated with the eigenvectors in linear transformation. The word ‘Eigen’ is of German Origin which means ‘characteristic’. Hence, these are the characteristic value that indicates the factor by which eigenvectors are stretched in their direction. It doesn’t involve the change in the direction of the vector except when the eigenvalue is negative. When the eigenvalue is negative the direction is just reversed. The equation for eigenvalue is given by

Av = λv

where A is the matrix

v is associated eigenvector

λ is scalar eigenvalue

Eigenvectors for square matrices are defined as non-zero vector values which when multiplied by the square matrices give the scaler multiple of the vector, i.e. we define an eigenvector for matrix A to be “v” if it specifies the condition, Av = λv

The scaler multiple λ in the above case is called the eigenvalue of the square matrix. We always have to find the eigenvalues of the square matrix first before finding the eigenvectors of the matrix.

For any square matrix, A of order n × n the eigenvector is the column matrix of order n × 1. If we find the eigenvector of the matrix A by, Av = λv, “v” in this is called the right eigenvector of the matrix A and is always multiplied to the right-hand side as matrix multiplication is not commutative in nature. In general, when we find the eigenvector it is always the right eigenvector.

We can also find the left eigenvector of the square matrix A by using the relation, vA = vλ

Here, v is the left eigenvector and is always multiplied to the left-hand side. If matrix A is of order n × n then v is a column matrix of order 1 × n.

Eigenvector Equation
The Eigenvector equation is the equation that is used to find the eigenvector of any square matrix. The eigenvector equation is,
Av = λv

where,
A is the given square matrix
v is the eigenvector of matrix A
λ is any scaler multiple

In linear algebra, eigendecomposition is the factorization of a matrix into a canonical form, whereby the matrix is represented in terms of its eigenvalues and eigenvectors. Only diagonalizable matrices can be factorized in this way

In [ ]:
from numpy import array
from numpy.linalg import eig
# define matrix
A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)
# calculate eigendecomposition
values, vectors = eig(A)
print(values)
print(vectors)

##  Q2. What is eigen decomposition and what is its significance in linear algebra?

Ans-In linear algebra, eigendecomposition is the factorization of a matrix into a canonical form, whereby the matrix is represented in terms of its eigenvalues and eigenvectors. Only diagonalizable matrices can be factorized in this way.

Eigenvalues are associated with eigenvectors in Linear algebra. Both terms are used in the analysis of linear transformations. Eigenvalues are the special set of scalar values that is associated with the set of linear equations most probably in the matrix equations.

## Q3. What are the conditions that must be satisfied for a square matrix to be diagonalizable using the
# Eigen-Decomposition approach? Provide a brief proof to support your answer.

Ans- matrix is diagonalizable if and only if its nilpotent part is zero. Put in another way, a matrix is diagonalizable if each block in its Jordan form has no nilpotent part; i.e., each "block" is a one-by-one matrix

Eigendecomposition is a technique used in Linear Algebra to break down a matrix into its constituent parts.

Let’s use a simple matrix to understand how Eigendecomposition is derived.

Suppose we have a 2 x 2 square matrix A:

Matrix

Our first step is to determine its eigenvalues and eigenvectors. If you compute the eigenvalues, you should get:

Eigenvalues

The corresponding eigenvectors to these eigenvalues are:

Eigenvectors

When we normalize our eigenvectors, we should see the following output:

Normalized-eigenvectors

We can develop the following equations using these components because they explain eigenvalues and eigenvectors:

Au1=λ1u1
Au2=λ2u2
If we compress these two systems into a matrix of eigenvectors and a matrix of eigenvalues, we get:

Matrix-equation

We can also use the following formula:

Matrices

When we use U
 and λ
 in equation (i)
, we get the following equation:

AU=UΛ
To get our matrix A
 from this relationship, we take U
 inverse, i.e., U−1
, on both sides of the matrix equation above. We end up with the equation below:

A=UΛU−1
This component is what we call Eigendecomposition. Matrix U
 contains eigenvectors and Λ
 has eigenvalues.

Why is this matrix decomposition important?

As stated, a matrix is a transformation that maps a vector from one point to another in the vector space.

In machine learning algorithms, we often apply such transformations several times until the final output is obtained at each phase of the algorithm.

However, the application also depends on the complexity of the problem. This means at the end, we will have taken our matrix raised to a power of a certain number.

To understand this, suppose we have the following square matrix:

AP
, where p=16
A simple approach to computing this matrix is to take the product of all possible pairs at each iteration.

Let’s determine the number of iterations needed to compute this matrix until we get our final output as Ap

In [3]:
import numpy as np

In [4]:
# create our matrix
M = np.array([[1,2,1], [0,1,0], [1,0,1]])

In [5]:
print(M)

[[1 2 1]
 [0 1 0]
 [1 0 1]]


In [6]:
# getting the eigenvalues and eigenvector of M
Lambda, U =np.linalg.eig(M)

In [7]:
print(U)

[[ 7.07106781e-01 -7.07106781e-01  2.00093587e-17]
 [ 0.00000000e+00  0.00000000e+00  4.47213595e-01]
 [ 7.07106781e-01  7.07106781e-01 -8.94427191e-01]]


In [8]:
print(Lambda)

[2. 0. 1.]


We need Λ
 and U−1
 to calculate all components of our Eigendecomposition.

We will first utilize the Numpy inv() function to determine U−1
 using the inverse of U
, as demonstrated below:

In [10]:
#Gettng U inverse
inv_U = np.linalg.inv(U)
inv_U

array([[ 0.70710678,  1.41421356,  0.70710678],
       [-0.70710678,  1.41421356,  0.70710678],
       [ 0.        ,  2.23606798,  0.        ]])

Let’s compute Λ
 on the diagonal matrix. We will use the diag() function with the Lambda vector to obtain this matrix:

In [12]:
Λ = np.diag(Lambda)
Λ

array([[2., 0., 0.],
       [0., 0., 0.],
       [0., 0., 1.]])

Since we have the three components of our eigendecomposition, let’s reconstruct the original matrix:

In [15]:
def round(values, decs=0):  # we don't want to include decimal points in our returned matrix
  return np.round(values*10**decs)/(10**decs)

vec = np.dot(U,np.dot(Λ, inv_U)) # taking the product of our three matrices
round(vec, decs=0)

array([[ 1.,  2.,  1.],
       [ 0.,  1.,  0.],
       [ 1., -0.,  1.]])

## Q4. What is the significance of the spectral theorem in the context of the Eigen-Decomposition approach?
# How is it related to the diagonalizability of a matrix? Explain with an example.

Ans-Spectral Decomposition or time-frequency analysis (also time-frequency decomposition) is a method employed to aid in the interpretation of seismic data. Spectral decomposition can be performed on a multitude of attributes (frequency, dip, azimuth…), though the frequency is the most common.

Is spectral decomposition same as eigen decomposition?
Similarly, for the eigendecomposition (also known as eigenvalue decomposition, spectral decomposition, or diagonalization), I would say the following: An eigendecomposition describes the effect of a matrix A on a vector as a different 3-step process A=QΛQ−1: An invertible linear transformation 

The same methodology in math. An integer can be decomposed into prime factors, for example, 20 = 2 * 2 * 5, which means 20 is not divisible by 3, and any integer multiple of 20 will be divisible by 5.



In mathematics, particularly linear algebra and functional analysis, a spectral theorem is a result about when a linear operator or matrix can be diagonalized (that is, represented as a diagonal matrix in some basis). This is extremely useful because computations involving a diagonalizable matrix can often be reduced to much simpler computations involving the corresponding diagonal matrix. The concept of diagonalization is relatively straightforward for operators on finite-dimensional vector spaces but requires some modification for operators on infinite-dimensional spaces. In general, the spectral theorem identifies a class of linear operators that can be modeled by multiplication operators, which are as simple as one can hope to find. In more abstract language, the spectral theorem is a statement about commutative C*-algebras. See also spectral theory for a historical perspective.

Examples of operators to which the spectral theorem applies are self-adjoint operators or more generally normal operators on Hilbert spaces.

The spectral theorem also provides a canonical decomposition, called the spectral decomposition, of the underlying vector space on which the operator acts.

## Q5. How do you find the eigenvalues of a matrix and what do they represent?

Ans-Eigenvalues represent the scaling factor by which a vector is transformed when a linear transformation is applied, while eigenvectors represent the directions in which the transformation occurs.

Take the identity matrix I whose order is the same as A.

Multiply every element of I by λ to get λI.

Subtract λI from A to get A - λI.

Find its determinant.

Set the determinant to zero and solve for λ.

## Q6. What are eigenvectors and how are they related to eigenvalues?

Ans-Eigenvalues represent the scaling factor by which a vector is transformed when a linear transformation is applied, while eigenvectors represent the directions in which the transformation occurs.

## Q7. Can you explain the geometric interpretation of eigenvectors and eigenvalues?

Ans-Vectors can be represented geometrically by arrows (directed line segments). The arrowhead indicates the direction of the vector, and the length of the arrow describes the magnitude of the vector. →PQ,v,or→v. We often write v=→PQ.

An eigenvector, corresponding to a real nonzero eigenvalue for that matrix, points in a direction in which it is stretched by the transformation, and is neither rotated nor sheared. The eigenvalue is the factor by which an eigenvector is stretched. If the eigenvalue is negative, the direction is reversed

## Q8. What are some real-world applications of eigen decomposition?

Ans-Eigendecomposition provides us with a tool to decompose a matrix by discovering the eigenvalues and the eigenvectors. This operation can prove useful since it allows certain matrix operations to be easier to perform and it also tells us important facts about the matrix itself.

Many applications of matrices in both engineering and science utilize eigenvalues and, sometimes, eigenvectors. Control theory, vibration analysis, electric circuits, advanced dynamics and quantum mechanics are just a few of the application areas.

## Q9. Can a matrix have more than one set of eigenvectors and eigenvalues?

Ans-Since a nonzero subspace is infinite, every eigenvalue has infinitely many eigenvectors. (For example, multiplying an eigenvector by a nonzero scalar gives another eigenvector.) On the other hand, there can be at most n linearly independent eigenvectors of an n × n matrix, since R n has dimension n .

The matrix A always has two eigenvalues, but sometimes they have algebraic multiplicity 2 or are complex numbers. If the matrix A has two complex eigenvalues, then it also has two linearly independent real eigenvectors.

## Q10. In what ways is the Eigen-Decomposition approach useful in data analysis and machine learning?
# Discuss at least three specific applications or techniques that rely on Eigen-Decomposition.

Ans-An eigendecomposition is calculated on a square matrix using an efficient iterative algorithm, of which we will not go into the details.

Often an eigenvalue is found first, then an eigenvector is found to solve the equation as a set of coefficients.

The eigendecomposition can be calculated in NumPy using the eig() function.

The example below first defines a 3×3 square matrix. The eigendecomposition is calculated on the matrix returning the eigenvalues and eigenvectors.

In [2]:
from numpy import array
from numpy.linalg import eig
# define matrix
A = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)
# calculate eigendecomposition
values, vectors = eig(A)
print(values)
print(vectors)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]
