## Q1- What is data encoding? How is it useful in data science?

Ans- Encoding is the process of converting the data or a given sequence of characters,symbols,alphabets etc.into a specified format,for the secured transmission of data.Decoding is the reverse process of encoding which is to extract the information from the converted format.

data preparation is a mandatory task. There are various tasks we require to perform in the data preparation. Encoding categorical data is one of such tasks which is considered crucial. As we know, most of the data in real life come with categorical string values and most of the machine learning models work with integer values only and some with other different values which can be understandable for the model. All models basically perform mathematical operations which can be performed using different tools and techniques. But the harsh truth is that mathematics is totally dependent on numbers. So in short we can say most of the models require numbers as the data, not strings or not anything else and these numbers can be float or integer. 

## Q2-What is nominal encoding? Provide an example of how you would use it in a real-world scenario.

Ans-Nominal encoding is used to transform categorical data into numerical data by assigning a unique numerical value to each category in a feature.

Nominal data: This type of categorical data consists of the name variable without any numerical values. For example, in any organization, the name of the different departments like research and development department, human resource department, accounts and billing department etc.



In [1]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
## create  a simple dataframe
df=pd.DataFrame({'color':['red','blue','green','purple','red','green','blue']})

In [3]:
df.head()

color
0     red
1    blue
2   green
3  purple
4     red

In [4]:
## create an instance of Onehotencoder
encoder=OneHotEncoder()

In [5]:
## perform fit and transform
encoded=encoder.fit_transform(df[['color']]).toarray()

In [6]:
import pandas as pd
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())


In [7]:
encoder_df

color_blue  color_green  color_purple  color_red
0         0.0          0.0           0.0        1.0
1         1.0          0.0           0.0        0.0
2         0.0          1.0           0.0        0.0
3         0.0          0.0           1.0        0.0
4         0.0          0.0           0.0        1.0
5         0.0          1.0           0.0        0.0
6         1.0          0.0           0.0        0.0

## Q3-In what situations is nominal encoding preferred over one-hot encoding? Provide a practical example.

ANS-For example, consider a dataset containing information about different types of fruit. One-hot encoding would create a separate column for each type of fruit, with a value of 1 indicating that the row contains data about that fruit and a value of 0 indicating that it does not

In [8]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [9]:
## create a simple dataframe
df = pd.DataFrame({
    'fruits':['Mango','Banana','Apple','Papaya','Orange','Kiwi','Orange','Apple']
})

In [10]:
df.head()

fruits
0   Mango
1  Banana
2   Apple
3  Papaya
4  Orange

In [11]:
## create an instance of Onehotencoder
encoder=OneHotEncoder()

In [12]:
## create an instance of Onehotencoder
encoded=encoder.fit_transform(df[['fruits']]).toarray()

In [13]:
import pandas as pd
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [14]:
encoder_df

fruits_Apple  fruits_Banana  fruits_Kiwi  fruits_Mango  fruits_Orange  \
0           0.0            0.0          0.0           1.0            0.0   
1           0.0            1.0          0.0           0.0            0.0   
2           1.0            0.0          0.0           0.0            0.0   
3           0.0            0.0          0.0           0.0            0.0   
4           0.0            0.0          0.0           0.0            1.0   
5           0.0            0.0          1.0           0.0            0.0   
6           0.0            0.0          0.0           0.0            1.0   
7           1.0            0.0          0.0           0.0            0.0   

   fruits_Papaya  
0            0.0  
1            0.0  
2            0.0  
3            1.0  
4            0.0  
5            0.0  
6            0.0  
7            0.0

In [15]:
## for new data
encoder.transform([['Kiwi']]).toarray()

/opt/conda/lib/python3.10/site-packages/sklearn/base.py:409: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 1., 0., 0., 0.]])

In [16]:
pd.concat([df,encoder_df],axis=1)

fruits  fruits_Apple  fruits_Banana  fruits_Kiwi  fruits_Mango  \
0   Mango           0.0            0.0          0.0           1.0   
1  Banana           0.0            1.0          0.0           0.0   
2   Apple           1.0            0.0          0.0           0.0   
3  Papaya           0.0            0.0          0.0           0.0   
4  Orange           0.0            0.0          0.0           0.0   
5    Kiwi           0.0            0.0          1.0           0.0   
6  Orange           0.0            0.0          0.0           0.0   
7   Apple           1.0            0.0          0.0           0.0   

   fruits_Orange  fruits_Papaya  
0            0.0            0.0  
1            0.0            0.0  
2            0.0            0.0  
3            0.0            1.0  
4            1.0            0.0  
5            0.0            0.0  
6            1.0            0.0  
7            0.0            0.0

## Q4Suppose you have a dataset containing categorical data with 5 unique values. Which encoding
# echnique would you use to transform this data into a format suitable for machine learning algorithms?
# Explain why you made this choice.

In [17]:
import pandas as pd
df = pd.DataFrame({'col1':['sun','sun','moon','earth','moon','venus']})
print('The original data')
print(df)
print('*' * 30)
df_new = pd.get_dummies(df, columns=['col1'],prefix='Planet')
print('The transform data using get_dummies')
print(df_new)
    

The original data
    col1
0    sun
1    sun
2   moon
3  earth
4   moon
5  venus
******************************
The transform data using get_dummies
   Planet_earth  Planet_moon  Planet_sun  Planet_venus
0             0            0           1             0
1             0            0           1             0
2             0            1           0             0
3             1            0           0             0
4             0            1           0             0
5             0            0           0             1


In [18]:
import pandas as pd
ids = [10,20,30,40,50,60,70]
state = ['Rajasthan','Odisha','U.P','M.P','Kerala','Goa','Bihar']
df = pd.DataFrame(list(zip(ids,state)),
                  columns=['Ids','Cities'])

In [19]:
df.head()

Ids     Cities
0   10  Rajasthan
1   20     Odisha
2   30        U.P
3   40        M.P
4   50     Kerala

In [20]:
from sklearn.preprocessing import OneHotEncoder 

In [21]:
x = [[11, "Seattle"], [22, "London"], [33, "Lahore"], [44, "Berlin"], [55, "Abuja"]]
y = OneHotEncoder().fit_transform(x).toarray()
print(y)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0. 0. 0.]]


## Q5-In a machine learning project, you have a dataset with 1000 rows and 5 columns. Two of the columns
# are categorical, and the remaining three columns are numerical. If you were to use nominal encoding to
# transform the categorical data, how many new columns would be created? Show your calculations.

In [24]:
import pandas as pd

data = {'product': ['computer', 'tablet', 'printer', 'laptop'],
        'price': [850, 200, 150, 1300]
        }

df = pd.DataFrame(data)

print(df)

    product  price
0  computer    850
1    tablet    200
2   printer    150
3    laptop   1300


In [26]:
import pandas as pd

#create DataFrame
df = pd.DataFrame({'points': [25, 12, 15, 14, 19, 23],
                   'assists': [5, 7, 7, 9, 12, 9],
                   'rebounds': [11, 8, 10, 6, 6, 5]})


In [27]:
df.head()

points  assists  rebounds
0      25        5        11
1      12        7         8
2      15        7        10
3      14        9         6
4      19       12         6

In [28]:
# importing pandas as pd
import pandas as pd
 
# list of name, degree, score
nme = ["aparna", "pankaj", "sudhir", "Geeku"]
deg = ["MBA", "BCA", "M.Tech", "MBA"]
scr = [90, 40, 80, 98]
 
# dictionary of lists
dict = {'name': nme, 'degree': deg, 'score': scr}
     
df = pd.DataFrame(dict)
 
print(df)

     name  degree  score
0  aparna     MBA     90
1  pankaj     BCA     40
2  sudhir  M.Tech     80
3   Geeku     MBA     98


In [17]:
import pandas as pd
import numpy as np

# Define the headers since the data does not have any
headers = ["symboling", "normalized_losses", "make", "fuel_type", "aspiration",
           "num_doors", "body_style", "drive_wheels", "engine_location",
           "wheel_base", "length", "width", "height", "curb_weight",
           "engine_type", "num_cylinders", "engine_size", "fuel_system",
           "bore", "stroke", "compression_ratio", "horsepower", "peak_rpm",
           "city_mpg", "highway_mpg", "price"]

# Read in the CSV file and convert "?" to NaN
df = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data",
                  header=None, names=headers, na_values="?" )
df.head()

symboling  normalized_losses         make fuel_type aspiration num_doors  \
0          3                NaN  alfa-romero       gas        std       two   
1          3                NaN  alfa-romero       gas        std       two   
2          1                NaN  alfa-romero       gas        std       two   
3          2              164.0         audi       gas        std      four   
4          2              164.0         audi       gas        std      four   

    body_style drive_wheels engine_location  wheel_base  ...  engine_size  \
0  convertible          rwd           front        88.6  ...          130   
1  convertible          rwd           front        88.6  ...          130   
2    hatchback          rwd           front        94.5  ...          152   
3        sedan          fwd           front        99.8  ...          109   
4        sedan          4wd           front        99.4  ...          136   

   fuel_system  bore  stroke compression_ratio horsepower  peak_rpm city_mpg  \
0         mpfi  3.47    2.68               9.0      111.0    5000.0       21   
1         mpfi  3.47    2.68               9.0      111.0    5000.0       21   
2         mpfi  2.68    3.47               9.0      154.0    5000.0       19   
3         mpfi  3.19    3.40              10.0      102.0    5500.0       24   
4         mpfi  3.19    3.40               8.0      115.0    5500.0       18   

   highway_mpg    price  
0           27  13495.0  
1           27  16500.0  
2           26  16500.0  
3           30  13950.0  
4           22  17450.0  

[5 rows x 26 columns]

In [18]:
df.dtypes

symboling              int64
normalized_losses    float64
make                  object
fuel_type             object
aspiration            object
num_doors             object
body_style            object
drive_wheels          object
engine_location       object
wheel_base           float64
length               float64
width                float64
height               float64
curb_weight            int64
engine_type           object
num_cylinders         object
engine_size            int64
fuel_system           object
bore                 float64
stroke               float64
compression_ratio    float64
horsepower           float64
peak_rpm             float64
city_mpg               int64
highway_mpg            int64
price                float64
dtype: object

In [22]:
obj_df = df.select_dtypes(include=['object']).copy()
obj_df.head()

make fuel_type aspiration num_doors   body_style drive_wheels  \
0  alfa-romero       gas        std       two  convertible          rwd   
1  alfa-romero       gas        std       two  convertible          rwd   
2  alfa-romero       gas        std       two    hatchback          rwd   
3         audi       gas        std      four        sedan          fwd   
4         audi       gas        std      four        sedan          4wd   

  engine_location engine_type num_cylinders fuel_system  
0           front        dohc          four        mpfi  
1           front        dohc          four        mpfi  
2           front        ohcv           six        mpfi  
3           front         ohc          four        mpfi  
4           front         ohc          five        mpfi

In [23]:
obj_df[obj_df.isnull().any(axis=1)]

make fuel_type aspiration num_doors body_style drive_wheels  \
27  dodge       gas      turbo       NaN      sedan          fwd   
63  mazda    diesel        std       NaN      sedan          fwd   

   engine_location engine_type num_cylinders fuel_system  
27           front         ohc          four        mpfi  
63           front         ohc          four         idi

In [24]:
obj_df["num_doors"].value_counts()

four    114
two      89
Name: num_doors, dtype: int64

In [25]:
obj_df = obj_df.fillna({"num_doors": "four"})

In [26]:
obj_df["body_style"] = obj_df["body_style"].astype('category')
obj_df.dtypes

make                 object
fuel_type            object
aspiration           object
num_doors            object
body_style         category
drive_wheels         object
engine_location      object
engine_type          object
num_cylinders        object
fuel_system          object
dtype: object

In [27]:
obj_df["body_style_cat"] = obj_df["body_style"].cat.codes
obj_df.head()

make fuel_type aspiration num_doors   body_style drive_wheels  \
0  alfa-romero       gas        std       two  convertible          rwd   
1  alfa-romero       gas        std       two  convertible          rwd   
2  alfa-romero       gas        std       two    hatchback          rwd   
3         audi       gas        std      four        sedan          fwd   
4         audi       gas        std      four        sedan          4wd   

  engine_location engine_type num_cylinders fuel_system  body_style_cat  
0           front        dohc          four        mpfi               0  
1           front        dohc          four        mpfi               0  
2           front        ohcv           six        mpfi               2  
3           front         ohc          four        mpfi               3  
4           front         ohc          five        mpfi               3

In [28]:
pd.get_dummies(obj_df, columns=["drive_wheels"]).head()

make fuel_type aspiration num_doors   body_style engine_location  \
0  alfa-romero       gas        std       two  convertible           front   
1  alfa-romero       gas        std       two  convertible           front   
2  alfa-romero       gas        std       two    hatchback           front   
3         audi       gas        std      four        sedan           front   
4         audi       gas        std      four        sedan           front   

  engine_type num_cylinders fuel_system  body_style_cat  drive_wheels_4wd  \
0        dohc          four        mpfi               0                 0   
1        dohc          four        mpfi               0                 0   
2        ohcv           six        mpfi               2                 0   
3         ohc          four        mpfi               3                 0   
4         ohc          five        mpfi               3                 1   

   drive_wheels_fwd  drive_wheels_rwd  
0                 0                 1  
1                 0                 1  
2                 0                 1  
3                 1                 0  
4                 0                 0

In [29]:
pd.get_dummies(obj_df, columns=["body_style", "drive_wheels"], prefix=["body", "drive"]).head()

make fuel_type aspiration num_doors engine_location engine_type  \
0  alfa-romero       gas        std       two           front        dohc   
1  alfa-romero       gas        std       two           front        dohc   
2  alfa-romero       gas        std       two           front        ohcv   
3         audi       gas        std      four           front         ohc   
4         audi       gas        std      four           front         ohc   

  num_cylinders fuel_system  body_style_cat  body_convertible  body_hardtop  \
0          four        mpfi               0                 1             0   
1          four        mpfi               0                 1             0   
2           six        mpfi               2                 0             0   
3          four        mpfi               3                 0             0   
4          five        mpfi               3                 0             0   

   body_hatchback  body_sedan  body_wagon  drive_4wd  drive_fwd  drive_rwd  
0               0           0           0          0          0          1  
1               0           0           0          0          0          1  
2               1           0           0          0          0          1  
3               0           1           0          0          1          0  
4               0           1           0          1          0          0

In [30]:
from sklearn.preprocessing import OrdinalEncoder

ord_enc = OrdinalEncoder()
obj_df["make_code"] = ord_enc.fit_transform(obj_df[["make"]])
obj_df[["make", "make_code"]].head(11)

make  make_code
0   alfa-romero        0.0
1   alfa-romero        0.0
2   alfa-romero        0.0
3          audi        1.0
4          audi        1.0
5          audi        1.0
6          audi        1.0
7          audi        1.0
8          audi        1.0
9          audi        1.0
10          bmw        2.0

In [31]:
from sklearn.preprocessing import OneHotEncoder

oe_style = OneHotEncoder()
oe_results = oe_style.fit_transform(obj_df[["body_style"]])
pd.DataFrame(oe_results.toarray(), columns=oe_style.categories_).head()

convertible hardtop hatchback sedan wagon
0         1.0     0.0       0.0   0.0   0.0
1         1.0     0.0       0.0   0.0   0.0
2         0.0     0.0       1.0   0.0   0.0
3         0.0     0.0       0.0   1.0   0.0
4         0.0     0.0       0.0   1.0   0.0

In [32]:
obj_df = obj_df.join(pd.DataFrame(oe_results.toarray(), columns=oe_style.categories_))

## Q6-You are working with a dataset containing information about different types of animals, including their
# species, habitat, and diet. Which encoding technique would you use to transform the categorical data into
# a format suitable for machine learning algorithms? Justify your answer.

In [35]:
pip install category_encoders

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.2/81.2 kB 2.2 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [40]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [43]:
import category_encoders as ce
import pandas as pd
data=pd.DataFrame({'City':[
'Delhi','Mumbai','Hydrabad','Chennai','Bangalore','Delhi','Hydrabad','Bangalore','Delhi'
]})

#Create object for one-hot encoding
encoder=ce.OneHotEncoder(cols='City',handle_unknown='return_nan',return_df=True,use_cat_names=True)

#Original Data
data

City
0      Delhi
1     Mumbai
2   Hydrabad
3    Chennai
4  Bangalore
5      Delhi
6   Hydrabad
7  Bangalore
8      Delhi

In [44]:
# fit and transform data
data_encoded = encoder.fit_transform(data)
data_encoded

City_Delhi  City_Mumbai  City_Hydrabad  City_Chennai  City_Bangalore
0         1.0          0.0            0.0           0.0             0.0
1         0.0          1.0            0.0           0.0             0.0
2         0.0          0.0            1.0           0.0             0.0
3         0.0          0.0            0.0           1.0             0.0
4         0.0          0.0            0.0           0.0             1.0
5         1.0          0.0            0.0           0.0             0.0
6         0.0          0.0            1.0           0.0             0.0
7         0.0          0.0            0.0           0.0             1.0
8         1.0          0.0            0.0           0.0             0.0

In [45]:
#encode the data
data_encoded=pd.get_dummies(data=data,drop_first=True)
data_encoded

City_Chennai  City_Delhi  City_Hydrabad  City_Mumbai
0             0           1              0            0
1             0           0              0            1
2             0           0              1            0
3             1           0              0            0
4             0           0              0            0
5             0           1              0            0
6             0           0              1            0
7             0           0              0            0
8             0           1              0            0

In [46]:
encoder.fit_transform(data)

City_Delhi  City_Mumbai  City_Hydrabad  City_Chennai  City_Bangalore
0         1.0          0.0            0.0           0.0             0.0
1         0.0          1.0            0.0           0.0             0.0
2         0.0          0.0            1.0           0.0             0.0
3         0.0          0.0            0.0           1.0             0.0
4         0.0          0.0            0.0           0.0             1.0
5         1.0          0.0            0.0           0.0             0.0
6         0.0          0.0            1.0           0.0             0.0
7         0.0          0.0            0.0           0.0             1.0
8         1.0          0.0            0.0           0.0             0.0

##  Q7-You are working on a project that involves predicting customer churn for a telecommunications
# company. You have a dataset with 5 features, including the customer's gender, age, contract type,
# monthly charges, and tenure. Which encoding technique(s) would you use to transform the categorical
# data into numerical data? Provide a step-by-step explanation of how you would implement the encoding.